[theme]
base = "light"
primaryColor = "#1D8178"
backgroundColor = "#F6F8F7"
secondaryBackgroundColor = "#EAF2F0"
textColor = "#172331"
font = "sans serif"

[server]
enableCORS = false
enableXsrfProtection = true

[browser]
gatherUsageStats = false

[theme.sidebar]
backgroundColor = "#172331"
secondaryBackgroundColor = "#243849"
textColor = "#EAF2F0"
primaryColor = "#83D0C4"
font = "sans serif"
